### ISSUE TITLE
Add Example for Custom UUIDs

### ISSUE THREAD

**Issue by zerox1212** [adafruit/Adafruit_nRF52_Arduino#111]
Can you please add an example where the service and characteristic UUIDs are custom instead of using predefined ones (like Heart Rate Monitor). I can't find any examples of creating a 128 bit UUID. It appears that passing a "normal" UUID string to `BLEService` is not possible.

Would be even nicer if constructor accepted a string.

**Comment by hathach** [comment]
check out the bleuart implementation https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/src/services/BLEUart.cpp#L45

**Comment by zerox1212** [comment]
Sorry I missed that one. Constructing with a string would still be convenient though. Thanks.
