### ISSUE TITLE
Clarification on SetFixedLength

### ISSUE THREAD

**Issue by zerox1212** [adafruit/Adafruit_nRF52_Arduino#112]
The documentation states that this is the length of the message in BYTES, but I don't see anything that specifies if `myCharactersitic.notify()` only takes a byte array.

Is it possible to `setFixedLenth(2)` and call `x.notify(myUINT16_T, 2)`? Or does all data need to get split into bytes before sending to the other end?

**Comment by hathach** [comment]
for support question, please post it in the support forum. Thanks

**Comment by hathach** [comment]
you can use notify(&num16, 2) . Or use notify16(num16) with lates 0.8.0 release
