### ISSUE TITLE
isCharging() function in software?

### ISSUE THREAD

**Issue by chaffneue** [adafruit/Adafruit_nRF52_Arduino#118]
I don't see an API exposed for telling if the device is charging. I'm looking to create a breathing effect on the panel's LED when the device is being charged and then having the LED turned to off when the charge cycle is complete, but all I have is an ADC battery voltage value on pin 31. I guess I could loop in the "USB" 5V output through a voltage divider and use a relatively high battery voltage reading to infer the charging is done, but if there's a way to do it that doesn't use GPIO pin and more components I'd love to know. Any creative ways to get a isCharging() type function within the framework? Am I just missing it?

**Comment by hathach** [comment]
There is unfortunately no such as function. This question is possibly better posted on the support forum where there would be more people know more about this
