### ISSUE TITLE
Increase size of Nffs partition

### ISSUE THREAD

**Issue by pbecchi** [adafruit/Adafruit_nRF52_Arduino#119]
I am using Nffs file system in my application, but flash memory available for Nffs is really to small!
There is any way to change definition of partition sizes?
Do I need a different bootloader?

I couldn't t find any documentation on nRF52 file system , where can I get some info?

**Comment by hathach** [comment]
There is a similar topic in support forum discussed this exact issue. Please follow posts and update post there if you still have trouble with nffs
