### ISSUE TITLE
I2C Transaction with no data causes .endTransmission() to hang

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_nRF52_Arduino#121]
See: https://forums.adafruit.com/viewtopic.php?f=57&t=131399

```
Wire.beginTransmission( 32 );

if( Wire.endTransmission() == 0 ) {
// slave found
}
```

**Comment by hathach** [comment]
issue is fixed on sandeep repo a month ago, just merged and pushed
 
https://github.com/sandeepmistry/arduino-nRF5/commit/91138312aaabd332b54cc46e2b89eb6f488270dc
