### ISSUE TITLE
Homekit ble 5.0 and mesh

### ISSUE THREAD

**Issue by jukorp** [adafruit/Adafruit_nRF52_Arduino#130]
How do I get activated mesh network? bluetooth 5.0 includes support mesh.
How can I do this?

**Comment by microbuilder** [comment]
There is no current mesh implementation in the BSP, and it isn't something we currently have planned at the moment. You'll have to look at the Nordic nRF5x SDK and mesh examples they provide, or something like Mynewt which provides a mesh implementation.
