### ISSUE TITLE
SoftwareTimer leaks memory

### ISSUE THREAD

**Issue by MZachmann** [adafruit/Adafruit_nRF52_Arduino#142]
As far as I can tell the SoftwareTimer leaks a system timer when deleted. When I added a destructor:

    `~SoftwareTimer() { if(_handle != NULL) xTimerDelete(_handle, 0); }`

it stopped leaking.

**Comment by hathach** [comment]
Thanks, it is indeed leaked memory. Soft Timer is not used much, and we forgot about clean this up. Will be include in the next release
