### ISSUE TITLE
SoftwareSerial stopping ble

### ISSUE THREAD

**Issue by jbcullis** [adafruit/Adafruit_nRF52_Arduino#145]
Using the hrm example, as soon as I add the software serial begin line (ie. myserial.begin(9600)) ble stops working on the board.

**Comment by hathach** [comment]
Please make sure you are on the latest BSP 0.8.3. Then post your most simple sketch that cause the issue here.

**Comment by jbcullis** [comment]
Using 0.8.3 however I found that if I moved the software serial begin to after the ble setup everything works.

**Comment by hathach** [comment]
This behavior is mentioned multiple times already. Many of interrupt related code should be initialized after bluefruit.begin() since it enable Softdevice will take control of interrupt forwarding stuff.

**Comment by jbcullis** [comment]
Thanks
