### ISSUE TITLE
Check Servo PWM frequency

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_nRF52_Arduino#160]
hiya @hathach can you check the PWM frequency of the Servos? accordng to this person they are 640Hz instead of 50Hz?
https://forums.adafruit.com/viewtopic.php?f=57&t=137278

see also:
https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/68

**Comment by hathach** [comment]
Note to my self, check out #134

**Comment by ladyada** [comment]
@hathach hi thach - do you mind looking at this bug this week? we had a few questions about it. let me know if you need help setting up a test!

**Comment by hathach** [comment]
Ah sorry, I am a bit hooked up with usb. Will work on to resolve this.

**Comment by ladyada** [comment]
no worries, i know USB is very consuming :) perhaps in the next week, i think its just a divider somewhere for a timer.

**Comment by hathach** [comment]
thanks, I will update when i fixed this, hopefully still in this week.

**Comment by hathach** [comment]
should be fixed with 456cb4a628a71c2427bad076e36daf974642d1de
