### ISSUE TITLE
OTA DFU Key

### ISSUE THREAD

**Issue by lefedor** [adafruit/Adafruit_nRF52_Arduino#162]
To send firmware fro DFU manual tells I need sign it with very the same key was generated building bootloader. Can I obtain those keys (private.key at least)?
Or will bootloader accept just any DFU file generated in arduino sketch temp folder and I'm over-complicating things? Can You briefly guide steps for OTA with feather bootloader? (5.1.0 dual, s132).
Thanks for any information on the topick.

**Comment by hathach** [comment]
We didn't use the secure bootloader, so no keys or whatsoever is required. We will make a tutorial for OTA later on.

**Comment by lefedor** [comment]
Thank You for the fast response. Feather support is really awesome.
Sadly I haven't knew there is forum option, will check it.
