### ISSUE TITLE
wiring_analog_nRF52.c unuseful code

### ISSUE THREAD

**Issue by a5021** [adafruit/Adafruit_nRF52_Arduino#164]
The code at line 245 does nothing. The CH[n].PSELN register will have no effect unless differential mode is enabled.

**Comment by hathach** [comment]
```
NRF_SAADC->CH[0].PSELN = pin;
```
Is this one ? I am not really sure on this, we based our core & std peripheral on this repo https://github.com/sandeepmistry/arduino-nRF5

**Comment by a5021** [comment]
Yes. It is the code I've wrote about.  "nRF52832 Product Specification v1.4" states it has no effect to init PSLEN without differential mode selected. Please see page 359, Also it is a nonsense to connect both differential ADC inputs to a single pin.

**Comment by hathach** [comment]
Ok, I checked the specs, but I don't really understand how the Analog input SAADC works. I will play it safe (or coward) here and put this issue on hold until it become an issue or more people come to verify this. Thank you very much for the issue.
