### ISSUE TITLE
How to receive signals (Caps lock, Num lock) from PC side - HID keyboard

### ISSUE THREAD

**Issue by ginoji5** [adafruit/Adafruit_nRF52_Arduino#166]
For making wireless HID keyboard modules (with nRF52 feather), I want to know the method receive signals from PC side. (Num lock, Caps lock, etc.)
It is possible to input arbitrary keys at the present time, but we also want to get output from PC side as well.

**Comment by hathach** [comment]
Thank for raising the issue, it is output report. Seems like the BLEHidGeneric already support invoked callback when receiving an output from PC.
  
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/src/services/BLEHidGeneric.h#L114

Though it is not used by BLEHidAdafruit (with proper report id and callback for keyboard). The work should be minimal, we will try to fix it when we could take some rest from nrf52840 work.

**Comment by ginoji5** [comment]
I see.
I will look BLEHidGeneric.h, and study output report.

**Comment by hathach** [comment]
@ginoji5  I did a latest push to master that implement the keyboard led. Tested with my linux. Let's me know if it works for you (please also tell what is your OS as well).

**Comment by hathach** [comment]
this is all you need to call
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/examples/Peripheral/hid_keyboard/hid_keyboard.ino#L56

**Comment by ginoji5** [comment]
Thank you for the great update!
I tested with my Win10. The result was good.
Next time, I will test it on Raspberry pi zero w.

**Comment by hathach** [comment]
Great, Thanks for the update. I am glad it works for you. Some users actually have issue with windows and blehid. I will pull out a macos to test, if all major os works+rpi, then we could close this one.

**Comment by hathach** [comment]
@ginoji5  any issues so far, if not we will close this one and include it in the next release

**Comment by ginoji5** [comment]
On Raspberry pi , the test was good too. Thank you.

**Comment by AustinRhoads** [comment]
The solution is 404. Can anyone point me in the right irection?
