### ISSUE TITLE
attachInterrupt vs. SoftDevice

### ISSUE THREAD

**Issue by Nenik** [adafruit/Adafruit_nRF52_Arduino#171]
I have run into an issue when using GPIO interrupts.
If I call attachInterrupt() before Bluefruit.begin(), the Bluefruit.begin() fails with NRF_ERROR_SDM_INCORRECT_INTERRUPT_CONFIGURATION, which I suspect might be related to the interrupt priority used by the attachInterrput() implementation.
Calling Bluefruit.begin() first, the interrupr callback works well.
This would really be worth documenting at least.
But should the change in the interrupt priority fix the issue, that would be even better.

**Comment by hathach** [comment]
Ah yeah, it is mentioned multiple times in the forum. Bluefruit.begin() enable sd, which will affect the vector table in some ways. Some irq may not work if called before that. We haven't looked into the details to resolve this, maybe later when we got more free time.

**Comment by Nenik** [comment]
Pull request: https://github.com/adafruit/Adafruit_nRF52_Arduino/pull/179

**Comment by hathach** [comment]
thanks for PR, this should be fixed already.
