### ISSUE TITLE
Version 0.8.5 can't compile on windows

### ISSUE THREAD

**Issue by craiq** [adafruit/Adafruit_nRF52_Arduino#174]
Hey,

OS: Windows 10 Pro 64-Bit (10.0, Build 15063)
Arduino IDE 1.8.6

after updating to version 0.8.5 I get following compiler error:

```
[18560] Failed to execute script __main__

Traceback (most recent call last):

  File "nordicsemi\__main__.py", line 315, in <module>

  File "site-packages\click\core.py", line 722, in __call__

  File "site-packages\click\core.py", line 697, in main

  File "site-packages\click\core.py", line 1066, in invoke

  File "site-packages\click\core.py", line 1066, in invoke

  File "site-packages\click\core.py", line 895, in invoke

  File "site-packages\click\core.py", line 535, in invoke

  File "nordicsemi\__main__.py", line 240, in genpkg

  File "site-packages\click\utils.py", line 259, in echo

  File "site-packages\click\_winconsole.py", line 180, in write

  File "site-packages\click\_winconsole.py", line 164, in write

OSError: Windows error 1

exit status -1
Fehler beim Kompilieren für das Board Adafruit Bluefruit nRF52 Feather.
```

going back to 0.8.4 solves the problem.

Tested this on the bleuart example.

**Comment by hathach** [comment]
can you post your full log of compilation.

**Comment by hathach** [comment]
Ah sorry, i didn't state it clear, can you enabled the verbose mode for compilation in preference. It provide a bit more information. You dont have to paste the full one, only the last command that trigger the error. it is probable `adafruit-nrfutil .......`

![image](https://user-images.githubusercontent.com/249515/44843105-b8697100-ac71-11e8-827a-b29da2e69e8e.png)

**Comment by craiq** [comment]
with this options activated there is no error anymore oO
deactivating it and it comes back

**Comment by hathach** [comment]
@craiq did you installed the win10 version from windows app store, or just a normal exe file from Arduino website ?

**Comment by craiq** [comment]
from the website

**Comment by hathach** [comment]
Thanks for reporting, we will try to fix this asap.

**Comment by clratzlaff** [comment]
I just installed Arduino IDE 1.8.6 onto my Windows 10 (10.0.17134 Build 17134) and had the exact same issue.  Enabling the verbose output solved the problem also.

**Comment by ladyada** [comment]
@craiq @clratzlaff try replacing your adafruit-nrfutil exec in Adafruit_nRF52_Arduino\tools\adafruit-nrfutil\win32 with this one and try again?

https://s3.amazonaws.com/uploads.hipchat.com/95690/1622213/Fkh16cYONkP3owE/adafruit-nrfutil.exe

if that fixes it we'll bump and re-release

**Comment by clratzlaff** [comment]
Thanks for the fix.  That fixed the problem.  I can now compile and upload without the verbose flags set.

**Comment by ladyada** [comment]
yay thanks for checking :)

**Comment by hathach** [comment]
We just release 0.8.6 that should fix this issue along with other minors issue. Thanks for posting.

**Comment by craiq** [comment]
back from holiday. thx its solved!
