### ISSUE TITLE
Segger Embbeded Studio for advance debugging

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Arduino#175]
SES is much better when coming to debugging, great for those that have jlink and better to develop our code.

**Comment by jeremypoulter** [comment]
FYI I have done some work to get the Adafruit Core running under Platform IO which is also good for advanced debugging - https://github.com/jeremypoulter/platform-nordicnrf52/tree/adafruit_nrf52_feather_intergration

**Comment by hathach** [comment]
Superb!! Thanks, I will be sure check that our for reference.

**Comment by Nenik** [comment]
@jeremypoulter Can you expand on the PIO integration?
I have tried setting up, even with "platform = https://github.com/platformio/platform-nordicnrf52.git
", but if I try to set the board to adafruit_feather_nrf52, I get:
Error: Unknown board ID 'adafruit_feather_nrf52'
I know little about Atom/PIO internals, but the github version does have adafruit_feather_nrf52.json
 under boards....

**Comment by Nenik** [comment]
OK, this seems to get me further, for reference:
platform = https://github.com/jeremypoulter/platform-nordicnrf52#adafruit_nrf52_feather_intergration
board = adafruit_feather_nrf52
framework = arduino

**Comment by jeremypoulter** [comment]
Right that is correct, FYI I also updated the example project, https://github.com/jeremypoulter/platformio-examples/tree/develop/wiring-blink

**Comment by romansoft** [comment]
@hathach, is there a SES project file you could share to get started with compiling and debugging in Segger Embedded Studio?

**Comment by hathach** [comment]
@romansoft unfortunately, I haven't started to do anything for this issue yet.

**Comment by jeremypoulter** [comment]
FYI PlatformIO now supports the Adafruit nRF boards, debugging works great ;-)

**Comment by hathach** [comment]
@jeremypoulter Superb!!! One of the issue with segger set up is the project is library only, it need the user sketch to complete the binary. I will close it for now, it is probably easier for user to use PlatformIO or segger ozone to troubleshoot the issue.
