### ISSUE TITLE
Undefined variable in Debug.cpp

### ISSUE THREAD

**Issue by JDowns1971** [adafruit/Adafruit_nRF52_Arduino#176]
lines 182, 183, and 188 "offset_fmt_size" is undeclared.
line 181 "format_size" is unused.

I assume "offset_format_size" should be replaced with "format_size" or vice versa.

Regards,

**Comment by hathach** [comment]
Ah, my bad. I just pushed the new update, along with the ascii ouput for that debug function as well. Please check to see if it works again.

**Comment by hathach** [comment]
thanks for reporting, I will close it now. If you have any issue, feel free to (re)open it
