### ISSUE TITLE
Enable >20 bytes on BLE

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_nRF52_Arduino#18]
By default, BLE and the nRF52 are limited to transmitting 20 bytes per packet, but there is a mechanism to transfer more data for higher throughput on supporting devices (on both ends of the connection).

An optional command should be added to the Bluefruit class to enable extended packets.

See the following thread for details: https://devzone.nordicsemi.com/question/95745/what-is-the-max-data-throughput-with-s132-v3/?answer=95750#post-id-95750

This should allow up to 244 bytes per transfer.

**Comment by TauqirH** [comment]
@hathach , was this feature ever implemented ? I think it's still 20 bytes.

**Comment by vChavezB** [comment]
was this problem solved ?
