### ISSUE TITLE
Is soft device still compatible for new Raytac module revision MDBT42Q-512KV2 

### ISSUE THREAD

**Issue by drcpattison** [adafruit/Adafruit_nRF52_Arduino#191]
Now that Raytac are using the 2nd revision of the nRF52832 chip for their modules, will the soft device still work with this new version?

Please see attached PDF from Raytac for details.

[nRF52832 Build Code Issue.pdf](https://github.com/adafruit/Adafruit_nRF52_Arduino/files/2482894/nRF52832.Build.Code.Issue.pdf)

**Comment by ladyada** [comment]
yep - should be fine
