### ISSUE TITLE
Confusing soft device version

### ISSUE THREAD

**Issue by wwwoholic** [adafruit/Adafruit_nRF52_Arduino#193]
I've added a call to dbgPrintVersion() function into the sketch and got this:
```
BSP Library     : 0.8.6
Firmware        : S132 2.0.1, 0.5.0 dual banks

```
However the manifest.json in the compiled DFU update .zip says:
```
{
    "manifest": {
        "application": {
            "bin_file": "peripheral_bleuart.ino.bin",
            "dat_file": "peripheral_bleuart.ino.dat",
            "init_packet_data": {
                "application_version": 4294967295,
                "device_revision": 65535,
                "device_type": 82,
                "firmware_crc16": 37128,
                "softdevice_req": [
                    136
                ]
            }
        },
        "dfu_version": 0.5
    }
}

```
It is my understanding that "softdevice_req" means required version of Soft Device, in which case this update should be rejected by DFU bootloader. And why manifest refers to 136 if the only SD included in 0.8.6 package is 132?

**Comment by hathach** [comment]
0.8.6 support both S132 v2 and S132 v5. Softdevice_req is Nordic 16bit number for ther production SD, also called SD firmware ID, you can look it up in nordic support site.
