### ISSUE TITLE
nRF52 not working with an Arducam, possibly i2c issue

### ISSUE THREAD

**Issue by MarcelRoehrl** [adafruit/Adafruit_nRF52_Arduino#199]
Hey,
I spend a lot of time trying to get the arducam 2MP mini camera (OV2640 ) to work with your feather boards. We need to get a camera to work with your board for our project. I already have several feather boards and arducams. There probably is a problem with the i2c connection.
I already opened an issue at in the Arducam git, but they couldn't help me.
Here is the issue with more details:
https://github.com/ArduCAM/Arduino/issues/359
It'd be a big help if you could help me to get this camera to work or tell me another camera that has been working with the nRF52832 feather board.

**Comment by hathach** [comment]
Hi, thank you for using Feather nRF52. For project's support like this one, it is better to post on our forum, there are many people and maker there that could help you out. The github issue is maintained by handful of people and only for bug fix and code development.
