### ISSUE TITLE
DFU from SD card

### ISSUE THREAD

**Issue by wwwoholic** [adafruit/Adafruit_nRF52_Arduino#201]
This is a feature request, not a bug. Many MCU modules or displays attached to them have SD card socket on board. It would be nice to have an option to trigger DFU by calling system utility function, something like UpdateFromSDCard(flename). This can simplify software distribution and updates "in the field", when using IDE is not an option.
According to [this post on Nordic forum](https://devzone.nordicsemi.com/f/nordic-q-a/31224/update-from-sdcard) there is fairly simple solution for this. Unfortunately I luck the experience to do it myself.

**Comment by hathach** [comment]
you should post this issue in the bootloader repo https://github.com/adafruit/Adafruit_nRF52_Bootloader
