### ISSUE TITLE
SoftwareTimer makes it impossible to share handlers

### ISSUE THREAD

**Issue by wwwoholic** [adafruit/Adafruit_nRF52_Arduino#203]
"private" on the _handle makes it impossible to use  TimerHandle_t parameter in TimerCallbackFunction_t implementation.
I suggest changing begin() function to return a handle, instead of void. This probably won't break existing code but will make it more useful going forward.

**Comment by hathach** [comment]
we could add an function to return handle called `getHandle()`. It is rather trivial, do you think you could folk our repo and submit an PR for this ?
