### ISSUE TITLE
How to use other pins for hardware I2C functions

### ISSUE THREAD

**Issue by qwert1213131** [adafruit/Adafruit_nRF52_Arduino#205]
In addition to pins 25 and 26, how to switch to other pins?

**Comment by hathach** [comment]
for questions or support, please post on our forum

**Comment by ericlangel** [comment]
i have the same question.

in the forum is no comment on this issue

**Comment by ladyada** [comment]
its definied in the variant
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/variants/feather_nrf52840_express/variant.h#L120

**Comment by ericlangel** [comment]
is it possible to implement a function like this:

void TwoWire::begin(uint8_t scl, uint8_t sda, uint32_t speed){
...
}
?

it's not nice to change the source code in the Hardware Librarys.

**Comment by ladyada** [comment]
nope, you should change it in the variant file
