### ISSUE TITLE
while (1) print loop stutters

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_nRF52_Arduino#206]
sorry this is being werid to find, this code starts-and-stops in an odd manner, perhaps delay(100) isn't taking care of interrupts?

```
void setup() {
  Serial.begin(115200);
  //while (!Serial);
    
  while (1) {
    Serial.println("-----------------------------");
    Serial.println("QSPI Test");
    Serial.println("-----------------------------");
    delay(100);
  }
}

void loop() {
}
```

**Comment by ladyada** [comment]
very odd ok - ill tr to get more information

**Comment by hathach** [comment]
@ladyada did you have time to look into this issue, it seems to work with me.

**Comment by ladyada** [comment]
not sure what it is, but it didn't happen again, ill close now - reopen if it happens again!
