### ISSUE TITLE
Ability to set Vendor ID/Device ID for raw HID bluetooth

### ISSUE THREAD

**Issue by darvin** [adafruit/Adafruit_nRF52_Arduino#212]
Would be nice if that would be added and exposed at https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/src/services/BLEHidGeneric.h

**Comment by hathach** [comment]
Do you have ref or information how to do that, or better an PR. Since I don't have any plan to work on HID any time soon.

**Comment by hathach** [comment]
closed due to lack of user's feedback
