### ISSUE TITLE
shortened local name when using custom uuid

### ISSUE THREAD

**Issue by ericlangel** [adafruit/Adafruit_nRF52_Arduino#217]
Hello,

if i'am using a custom 16bit uuid everything is fine. the advertised name is "testname" (complete Local Name)
code:
...
BLEService        hrms = BLEService(0x0A00);
...
Bluefruit.setName("testname");
...

if i'am using a custom 128Bit uuid, the advertised Name is "testn" (shortened local Name)
code:
...
uint8_t test[] = {0x00, 0x00, 0x00, 0x00, 0x00,0x00,0x00,0xb0,0x00,0x40,0x51,0x04,0x00,0x0a,0x00,0x00};
BLEService        hrms = BLEService(test);
...
Bluefruit.setName("testname");
...

is it a Bug? can i get the complete local name with custom 128bit uuid's?

**Comment by hathach** [comment]
Your adv data is too long, for question please post on forum support
