### ISSUE TITLE
BLEUart Device disconnects after [BLE   ] BLE_EVT_USER_MEM_REQUEST : Conn Handle = 0

### ISSUE THREAD

**Issue by khawajamechatronics** [adafruit/Adafruit_nRF52_Arduino#220]
Hi,

I am having issue with adafruit NRF52832 device. It works fine until
[BLE   ] BLE_EVT_USER_MEM_REQUEST : Conn Handle = 0
[BLE   ] BLE_GAP_EVT_DISCONNECTED : Conn Handle = 0
[GAP   ] Disconnect Reason 0x13
and device loses connection.

Can any one guide whats this issue and how to resolve?

Thanks

**Comment by khawajamechatronics** [comment]
More Logs.

Can anyone help?


[CFG   ] SoftDevice's RAM requires: 0x20002FA0
 MaxMtu:   247
Please use Adafruit's Bluefruit LE app to connect in UART mode
Once connected, enter character(s) that you wish to send

BSP Library : 0.9.3
Bootloader  : s132 6.1.1 r1
Serial No   : 

--------- SoftDevice Config ---------
Max UUID128     : 10
ATTR Table Size : 2048
Service Changed : 1
Peripheral Connect Setting
  - Max MTU         : 247
  - Event Length    : 6
  - HVN Queue Size  : 3
  - WrCmd Queue Size: 1

--------- BLE Settings ---------
Name            : 
Max Connections : Peripheral = 1, Central = 0 
Address         :  (Static)
TX Power        : 4 dBm
Conn Intervals  : min = 20.00 ms, max = 30.00 ms
Conn Timeout    : 2000.00 ms
Peripheral Paired Devices:

**Comment by khawajamechatronics** [comment]
If its not solveable on this adafruit hardware then suggest me hardware which can work without any issue.

Issue happens when data bytes are sent more than 20.

Until 20 Bytes it works fine.

**Comment by hathach** [comment]
First, you need to tell us how to reproduce the issue: your sketch, which app and what to send etc ... Second, don't expect us to rush fixing the issue, we are working on multiple project and has our own agenda. 

If you are not happy with adafruit hardware, free fee to use others, google is your best adviser.

**Comment by khawajamechatronics** [comment]
Hi,

Thanks for prompt response. I am glad to provide all the information required to reproduce the issue so you can resolve it asap.

I am using bleuart example with Adafruit nrf52832 
BSP Library : 0.9.3
Bootloader  : s132 6.1.1 r1

A)I have tested the bluefruit app. Only 20 bytes data is successfully received but more than that is truncated.
B)Tested with NRF Connect App.
Similar issue, 20 bytes are sent successfully but more than 20 bytes it gives 

[BLE   ] BLE_EVT_USER_MEM_REQUEST : Conn Handle = 0
[BLE   ] BLE_GAP_EVT_DISCONNECTED : Conn Handle = 0
[GAP   ] Disconnect Reason 0x13

Method to reproduce.
Upload the blueuart example.
send more than 20 characters using nrfconnect app.

![image](https://user-images.githubusercontent.com/5573931/51866543-0bec0200-236b-11e9-84a2-61ae86adecd3.png)

I am have trust on Adafruit Hardware and due to that I purchased it. 

Obviously you are guru and if with your little attention issue is resolved it will definitely strengthen my trust on Adafruit hardware.

Its definitely not an App Issue, Issue seems to be with Datalength as it works until 20 bytes. I hope you have some quick solution or suggestion to resolve it.

**Comment by hathach** [comment]
Thanks for detail information, we will try to reproduce and analyze the issue when possible

**Comment by khawajamechatronics** [comment]
Any chance looking up at this?

**Comment by wlamprecht** [comment]
Hi @khawajamechatronics, 
did you try to request a bigger MTU size? 
By clicking on the three dots, right of "SERVER" and then Request MTU

**Comment by wlamprecht** [comment]
@khawajamechatronics I'm not working with Arduino. But you have to initiate the mtu size change request from the Gatt client. Look for something like GattClient exchange_mtu.

**Comment by khawajamechatronics** [comment]
Hi,

Thanks for your time. My actual app is different and it works with ESP32 without sending or requesting MTU (may be MTU is already configured max in ESP32 Software) So I can't make my app to send MTU request. I need to know a way to set max MTU inside Arduino Code. 

Thanks

**Comment by hathach** [comment]
just back from Lunar New Year, working on this issue now, it is part of the Long Write support #91

**Comment by hathach** [comment]
@khawajamechatronics I have implemented the LONG WRITE sequence support, that could handle > MTU bytes write (20 bytes by default) in the master branch. Please try to see if that work for you.

You will need to follow this guide to install BSP via git (master branch) to test, once verified we will include this into the next release. Thank you for your patient.

https://learn.adafruit.com/bluefruit-nrf52-feather-learning-guide/arduino-bsp-setup#advanced-option-manually-install-the-bsp-via-git-5-23

**Comment by khawajamechatronics** [comment]
Hi,

Thanks for resolving the long bytes issue. Yes it working for longer data than 20 bytes.

One issue is in some internal code 'Hello' appears with each data received.


![image](https://user-images.githubusercontent.com/5573931/53675508-cb104180-3cb8-11e9-802f-56d9a1b08583.png)


![image](https://user-images.githubusercontent.com/5573931/53675551-365a1380-3cb9-11e9-91b4-3df3631e9485.png)

**Comment by hathach** [comment]
Thanks for confirming, this issue is fixed, for the Hello it is likely leftover somewhere in your code. Please open another issue if it still exists.
