### ISSUE TITLE
Serial Bootloader doesnt work (0.9.3)

### ISSUE THREAD

**Issue by ericlangel** [adafruit/Adafruit_nRF52_Arduino#221]
Hello,

since i have updatet to Version 0.9.3 i cant flash via Serial Bootloader.

i flashed Bootloader "feather_nrf52832_bootloader-0.2.6_s132_6.1.1.hex"
and connect DTR (Reset), TX, RX, GND
P0.20 is left open

Opened serial port COM4
Starting DFU upgrade of type 4, SoftDevice size: 0, bootloader size: 0, application size: 48152
Sending DFU start packet
Timed out waiting for acknowledgement from device.
Sending DFU init packet

Failed to upgrade target. Error is: Attempting to use a port that is not open
Traceback (most recent call last):

With Version 0.9.1 i have no issues.
feather_nrf52832_bootloader_s132_6.1.1r0.hex
connected DTR (Reset), RX, TX, GND
P0.20 is left open

2nd issue:
with 0.9.3 i have more power consumption -> 3.98mA
with 0.9.1 i had 10µA!

**Comment by hathach** [comment]
This is not code related issue, please post your bootloader question in support forum. There is probably an answer for your question already there. For power issue, please open separated issue, make sure you test with one of our stock example sketch, and please provide more information there.
