### ISSUE TITLE
Add example for multiple connections in peripheral mode

### ISSUE THREAD

**Issue by zanimax12** [adafruit/Adafruit_nRF52_Arduino#230]
Please add an example or some documentation showing how to accept multiple connections in peripheral mode.

**Comment by hathach** [comment]
multiple peripherals connection is WIP, and not completed yet. We will sure add one when it is implemented

**Comment by hathach** [comment]
here it is https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/examples/Peripheral/bleuart_multi/bleuart_multi.ino
