### ISSUE TITLE
Question on Stability of Master

### ISSUE THREAD

**Issue by czuvich** [adafruit/Adafruit_nRF52_Arduino#231]
I noticed there are some new check-ins to the master branch.  I didn't see any updates to the libraries via Library Manager in the Arduino IDE.  Should I wait until an official release is published or is it pretty safe to grab the latest master branch?  I wasn't sure if you were committing to "develop" and then merging or what.  There's a few fixes in BLE that I'd like to grab.

**Comment by hathach** [comment]
you can give it a try, but master is wip, if you need stability, stay with the release or wait for our next release. Which works best for you.
