### ISSUE TITLE
Need a new define to better designate nRF52832

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_nRF52_Arduino#242]
This will help with `#define` usage for nRF52832 vs. nrf52840. See here:
https://github.com/adafruit/Adafruit_ILI9341/issues/44

Suggestions is to simply add `ARDUINO_NRF52832_FEATHER` via a `-D` command line:
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/boards.txt#L41

@hathach tagging you as requested.

**Comment by hathach** [comment]
post comment here since there are more people there https://github.com/adafruit/Adafruit_ILI9341/issues/44#issuecomment-473691065
