### ISSUE TITLE
failed to upgrade target

### ISSUE THREAD

**Issue by gyboy** [adafruit/Adafruit_nRF52_Arduino#244]
I use adruino-1.8.9 to flash my nrf52832 board ,just use the board manager to install the adafruit bluefruit board and successfully burn the bootloader V0.26 using jlink for bluefruit.After I had first verify and upload the bleuart example and try to run the beacon example,I can't upload the firmware ever again.The log show that

Timed out waiting for acknowledgement from device.
Failed to upgrade target. Error is: No data received on serial port. Not able to proceed.
Traceback (most recent call last):
 .......
nordicsemi.exceptions.NordicSemiException: No data received on serial port. Not able to proceed.

I read the manual that it seems need to update the bootloader,but the 0.26 is the newest version and I have tried to update so many time times,it still doesn't work.  I also try to enter the DFU mode but I can't see anything,What's the problem?
My systerm is Win7 X64

**Comment by hathach** [comment]
for question please post it in our support forum, there are more people there to help you out
