### ISSUE TITLE
ToDo: Add Central Mailbox Demo

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_nRF52_Arduino#25]
Create a Central demo with a mailbox pattern where:

- [ ] The Central device maintains a 'Mailbox' server, with a single mailbox for each device address (1KB per mailbox?)
- [ ] Mailbox data can be persisted to NFFS files (one file per address) for recovery at startup
- [ ] The Central advertises itself with a specific 'Mailbox Server' UUID in the advertising packet
- [ ] Up to 7 links/mailboxes can be established
- [ ] Peripherals can check for any message(s) in their own mailbox
- [ ] Peripherals can scan for other mailboxes on the Central, and retrieve the following information:
  - [ ] Device address
  - [ ] Device Name
  - [ ] RSSI value if connected
  - [ ] Timestamp when the peripheral was last connected
- [ ] Peripherals can write messages to *every* mailbox (using a global address like FF:FF:FF:FF:FF:FF?) or to a specific mailbox (using a specific device address)

This allows a reasonably complete Central example, solving a practical problem and allowing for a very simple star network with point to point (1:1) and point to multi-point (1:all) exchanges, without getting overly complex, allowing simple BLE based sensor networks.

Two examples sketches are required for this demo:

- [ ] The Central mailbox server (`mailbox_server` or `mailbox_central`)
- [ ] The Peripheral mailbox client (`mailbox_client` or `mailbox_peripheral`)

**Comment by hathach** [comment]
closed due to lack of activities
