### ISSUE TITLE
NRF52840 Dongle Application doesn't start after Unplug&Plug

### ISSUE THREAD

**Issue by ericlangel** [adafruit/Adafruit_nRF52_Arduino#253]
When i'am Upload my Sketch on the NRF Dongle everything works fine.

When i unplug the Dongle and plug it in again, the sketch doesn't start (did not advertise).

I have to open Arduino an open the COM Port of the Dongle.
Then the Dongle is Advertising (and of course printing some debug)

That did not work with HTERM.

I dont know if there is a Bug with the (unsupported) NRF52840 Dongle, or with the native NRF52840 USB or the Adafruit Library.
I have 2 NRF Dongles with the same behavior.

**Comment by hathach** [comment]
Example sketch wait for serial connection, comment it out will solve this.

  While(!Serial) delay(10):
