### ISSUE TITLE
What is different keyboardReport() to keyPress()?

### ISSUE THREAD

**Issue by Iyeonghun** [adafruit/Adafruit_nRF52_Arduino#256]
Developing on the **Adafruit Feather nRF52 Bluefruit LE** board. 
I'm going to use BLEHidAdafruit to develop the following features.
- keyboard input `shift + up` and `shift + down`

However, I don't know the difference between `keyboardReport()` and `keyPress().`

Can I refer to the guide on the **Bluefruit EZ-Key** board?
Is `keyCommand()` the same as `keyboardReport()`?

I'm waiting for your help.

**Comment by hathach** [comment]
for question, please post in our support forum. Short anwser: keycode vs anscii
