### ISSUE TITLE
[Bug] autoConnLed and Scan

### ISSUE THREAD

**Issue by czuvich** [adafruit/Adafruit_nRF52_Arduino#277]
BSP Library : 0.10.1
Board: nRF52840 Express
Bootloader : s140 6.1.1

I'm using the nRF52840 Express as a Central.  I have autoConnLed(true) and I am using the Bluefruit.Scanner.start((5 * 1000) / 10) = 5 second timeout.

When I get the stop callback, I would expect the blue LED to stop blinking; however, it keeps blinking.  The scanner is not running (verified by checking the isRunning()).

Is that expected behavior?

**Comment by hathach** [comment]
thanks for issue, we have fixed it and included this fix in the next release
