### ISSUE TITLE
BLEClientHidAdafruit compile error

### ISSUE THREAD

**Issue by seihan** [adafruit/Adafruit_nRF52_Arduino#279]
'HID_KEYCODE_TO_ASCII' was not declared in this scope

board: nRF52832, nRF52840
using Arduino 1.8.8

**Comment by hathach** [comment]
can you also tell us which bsp version and which example you got issue with

**Comment by seihan** [comment]
Yes, of course. I'm sorry.

BSP origin / master, central_hid example

`Arduino/hardware/Adafruit/Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/examples/Central/central_hid/central_hid.ino: In function 'void processKeyboardReport(hid_keyboard_report_t*)':
central_hid:209:24: error: 'HID_KEYCODE_TO_ASCII' was not declared in this scope
         ch = shifted ? HID_KEYCODE_TO_ASCII[kc].shifted : HID_KEYCODE_TO_ASCII[kc].ascii;`

**Comment by hathach** [comment]
You should only report the bug with release, master or develop is still work in progress. It is the conflict between ble and usb hid, I am focusing on usb just now, But thanks for the issue.
