### ISSUE TITLE
[Feature] Central void* on Callbacks

### ISSUE THREAD

**Issue by czuvich** [adafruit/Adafruit_nRF52_Arduino#280]
It'd be nice to pass a void* parameter to the connect() method of the Central and have it passed back from the callback.

Static callbacks are great, but if you're using classes then it becomes a pain to try and map callbacks to class instances.  It looks like ada_callback supports data; however, it's not implemented on the Central callback. 

Maybe it's because the Central only connects to one peripheral at a time?  Regardless, it'd still be nice.

**Comment by hathach** [comment]
connection handle is the common parameter and is used as ID for ble connection. You can use it as index of array holding any custom data for your need.
