### ISSUE TITLE
[Feature]Restore PIN_DFU define in varients

### ISSUE THREAD

**Issue by pyro9** [adafruit/Adafruit_nRF52_Arduino#309]
In 0.10.1, there was a useful #define PIN_DFU, why was it removed?

**Comment by hathach** [comment]
since the application doesn't use PIN_DFU at all. This pin is only in the interest of Bootloader project

**Comment by pyro9** [comment]
But applications may use the button attached to the pin. Perhaps PIN_DFU isn't the best name for that use, it is useful.

**Comment by hathach** [comment]
@pyro9 we just add the PIN_BUTTON1 for most variants, please try to use it instead.
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/variants/feather_nrf52840_express/variant.h#L61
