### ISSUE TITLE
NFC Hardware support

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Arduino#31]

**Comment by hathach** [comment]
https://devzone.nordicsemi.com/blogs/920/how-to-test-nrf52-nfc-tag-with-reader-adafruit-tag/

**Comment by microbuilder** [comment]
This has already been tested during development and confirmed working, though adding demo code that works with the SD and Bluefruit API remains as a ToDo ... though I think improved Central support is more critical at this stage.

**Comment by hathach** [comment]
Yeah, the issue reminds us to create some helper to make NFC using easier. But it is not urgent yet. Cental API is quite OK ( for single connection now).

**Comment by hathach** [comment]
We still haven't worked on NFC just yet. SDK has a strict license, so we didn't use any of its files, only subset of nrfx module for some prph driver. Nordic SDK has quite a bit of dependencies, I am not sure but it may require some effort to include its files for development. If you could oob pairing and willing to submit an PR, we will be more than happy to merge. :)

**Comment by hathach** [comment]
closed due to lack of activities
