### ISSUE TITLE
Cloudflare reject access

### ISSUE THREAD

**Issue by x893** [adafruit/Adafruit_nRF52_Arduino#329]
Hi,
https://www.adafruit.com/package_adafruit_index.json
reject request

Error 1020 Ray ID: 50922af3fee58db7 • 2019-08-20 06:04:05 UTC
Access denied
What happened?
This website is using a security service to protect itself from online attacks.

**Comment by ladyada** [comment]
hiya nothing we can do about it, you've been blocked by cloudflare, see if you're using a proxy and turn that off :)
