### ISSUE TITLE
[Feature] Additional Device Information

### ISSUE THREAD

**Issue by elral** [adafruit/Adafruit_nRF52_Arduino#335]
For my project I need to set additional device parameters. To do this I added some methods to BLEDis.cpp and BLEDis.h. It would be great if these additions could be added to the masterbranch.  Unfortenutely I do not know how to submit a pull request, therefore I addded my code here.

Thanks and regards

[BLEDis.zip](https://github.com/adafruit/Adafruit_nRF52_Arduino/files/3554159/BLEDis.zip)

Ralf

**Comment by hathach** [comment]
submit a PR is very simple, it is much easier for you and us than attaching zip file. Just create a folk, modify the code then submit PR. Here is the tutorial from github.
https://help.github.com/en/articles/creating-a-pull-request

**Comment by elral** [comment]
Thanks, I forked it and changed the files, but "unfortenutely" more than for this Pull Request. It seems that no files can be choosen for a Pull Request, so I have to start again. Will start next week.

**Comment by hathach** [comment]
You dont need to choose file, only need to modify, add file to github then commit and push. Then create the pr, github will do the rest for you
