### ISSUE TITLE
[Bug] BSP 0.14.0 - Bootloader missing

### ISSUE THREAD

**Issue by jpconstantineau** [adafruit/Adafruit_nRF52_Arduino#348]
**Describe the bug**
A fresh update (uninstall/install)  of the BSP top 0.14.0 on windows 10 removes the bootloader folder that should be located here: \AppData\Local\Arduino15\packages\adafruit\hardware\nrf52\0.14.0/bootloader/feather_nrf52832/feather_nrf52832_bootloader-0.2.13_s132_6.1.1.hex

**Set up (please complete the following information)**
  - nrf52832
  - Windows 10
  - Arduino IDE console:
nrfjprog.exe --program C:\Users\pierre\AppData\Local\Arduino15\packages\adafruit\hardware\nrf52\0.14.0/bootloader/feather_nrf52832/feather_nrf52832_bootloader-0.2.13_s132_6.1.1.hex -f nrf52 --chiperase --reset 
Parsing hex file.
**ERROR: The file specified could not be found**.
Error while burning bootloader.

**To Reproduce**
1. Install BSP 0.14.0
2. select nrf52832 feather as board
3. select jlink programmer
4. burn bootloadre
5. See error shown above

**Expected behavior**
Bootloaders should be included with the BSO to enable support of flashing bootloader from within arduino IDE

**Screenshots**
Not really needed...

**Comment by hathach** [comment]
ah right, thanks for reporting. I forgot to added those bootloader files. Will release an fix soon, along with other minor fixes.
