### ISSUE TITLE
[Feature] allow SPI creation with high speed SPIM3

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_nRF52_Arduino#351]
perhaps in the variant you can specify you want SPI/SPI1/etc to use the high speed SPIM3 periph. then we can have 32mhz instead of 8mhz for TFT for easy 4x speedup :)

**Comment by dhalbert** [comment]
Note that I was unable to get SPIM3 to work with the SoftDevice enabled: https://github.com/adafruit/circuitpython/issues/1222

**Comment by ladyada** [comment]
kk - here's some more demos i found
https://jimmywongbluetooth.wordpress.com/2019/10/05/lcd-display-on-nrf52840/

**Comment by hathach** [comment]
![image](https://user-images.githubusercontent.com/249515/66744091-b8442900-eea5-11e9-86d1-588448218680.png)
