### ISSUE TITLE
[Bug] check if Tone is blocking-only

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_nRF52_Arduino#353]
you got tone() working, it's great! however i forgot to verify if it blocks or not. Arduino tone() should return immediately, and then some time later the PWM stops. on nrf it seems like it is blocking only!

**Comment by hathach** [comment]
@ladyada sorry, somehow this got out of my radar. The nrf `tone()` should be non-blocking since it use PWM hardware.
