### ISSUE TITLE
[KUDOS] SystemOff Works Great!

### ISSUE THREAD

**Issue by czuvich** [adafruit/Adafruit_nRF52_Arduino#368]
I just wanted to say thanks for implementing the systemOff functionality.  I am able to power down the nRF52840 Express using the systemOff and a PCF8523 as an interrupt source (via alarm)!  The power consumption is great (700uA) considering the LED's and regulator on the board.  Thank you!

**Comment by hathach** [comment]
thanks, but you should not open an issue for a Kudos. Posting it on our support forum or power-related issue where others could find it more useful.
