### ISSUE TITLE
A customized unified sensor service ?

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Arduino#37]

**Comment by hathach** [comment]
an alternative would be OIC ?

**Comment by microbuilder** [comment]
OIC (now called OCF) is the way to move forward with this in a standard way but currently only Mynewt supports OCF. I think the best approach is to produce something with the Mynewt (nRF52 Pro) board family and codebase and judge interest from there about how to move forward on the Arduino side.

**Comment by microbuilder** [comment]
Closing this in favor of OCF and Iotivity which solves this problem using an open standard.
