### ISSUE TITLE
Error when compiling tensorflow lite on nrf52

### ISSUE THREAD

**Issue by yang12313** [adafruit/Adafruit_nRF52_Arduino#388]
**Describe the bug**
Error when compiling tensorflow lite  on nrf52 Arduino environment.
**Set up (please complete the following information)**
  - adafruit bluefruit feather nRF52832
  - Windows 10.

**To Reproduce**
1. Go to https://github.com/yang12313/tensorflow_lite_nRF52.git download the model.h and sketch_nov08a.ino
2. please download the associated library which can be found from the library manager
3. Once the setup is done, then click the compile button.
4. error is shown on the readme file.

**Comment by hathach** [comment]
seems to be an issue when compiling STL lib, I haven't compiled STL lib with arduino nrf core before.

**Comment by yang12313** [comment]
> seems to be an issue when compiling STL lib, I haven't compiled STL lib with arduino nrf core before.
 Thank you so much I am going to unload the STL lib to see if the program can run or not.

**Comment by bojh** [comment]
Hi @yang12313 
just done a little test with the hello_world example with nrf52840 Express board. The work around from [here](https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/272#issuecomment-510929376) is working. There a still warnings but it does compile and should run (not tested).

**Comment by hathach** [comment]
example should work with latest BSP of 0.20.5
