### ISSUE TITLE
"Error 1020 Access denied" on site

### ISSUE THREAD

**Issue by Chtobi** [adafruit/Adafruit_nRF52_Arduino#389]
**Describe the bug**
The same issue as : #329
"Error 1020 Access denied" pops up on www.adafruit.com

I didn't use any proxy or something, tried to open many times from different computers - no luck.

Cloudflare says, that the site firewall must be misconfigured:
https://community.cloudflare.com/t/community-tip-fixing-error-1020-access-denied/66439

**Comment by hathach** [comment]
please use support forum for non-code related issue
