### ISSUE TITLE
Pair with passkey

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Arduino#39]
Allow user to set/change passkey. Central must enter the correct PIN to pair
https://devzone.nordicsemi.com/question/122637/static-passkey-s132/

**Comment by steffensol** [comment]
Any news on this one?

**Comment by hathach** [comment]
not yet, I am too busy with other projects just now.

**Comment by mrzealot** [comment]
Bump! Would love to use this feature in a keyboard project...

**Comment by wero1414** [comment]
Hi @hathach  do you have any news on this issue?

Or at least a work-flow which i can follow to get this done?
