### ISSUE TITLE
Proper setup with external lipo battery

### ISSUE THREAD

**Issue by billyjoker** [adafruit/Adafruit_nRF52_Arduino#415]
Hi, i have read some issues related with the power consumption and i have no clear how to do a well setup to use the Adafruit with a battery. I did some tests with "standard" code but i see that the lipo batt is drained too fast, so my questions are below:

- Should i send a command code from my controller device (Android phone) to set the Adafruit as some as a "standby mode"?  I mean if exists something like power off and power on by BT commands. I do not if it is the called as "sleep mode" and "wake up"

- Should i add delays in the loop code in order to have less consumption? I've read some tips [here](https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/165)

- Exists any convenction to proceed when the lipo batt is almost empty? i mean, advice to the user when batt is under 5%

- When i put the charger, the lipo batt will be recharging automatically? Or maybe i should to manage something programatically.

I am newby using this Adafruit device and i need some patterns to start working well with it. Thanks in advance

**Comment by hathach** [comment]
For questions please post it to our support forum, you may want to check out other power related issue comment #51  #165
