### ISSUE TITLE
adafruit-nrfutil.exe is deleted after successful build.

### ISSUE THREAD

**Issue by eduards66** [adafruit/Adafruit_nRF52_Arduino#424]
**Describe the bug**
adafruit-nrfutil.exe is deleted from ...\\arduino-nightly\\portable\\packages\\adafruit\\hardware\\nrf52\\0.16.0/tools/adafruit-nrfutil/win32/ after successful build and then next time build will fail on

**Set up (please complete the following information)**
SET up:

arduino ide 1.8.11 hourly build 2020/01/08 12:33
Board: adafruit feather nRf52832,
bootloader 0.2.13 SoftDevice s132 6.1.1. Level0(Release)
windows10

**To Reproduce**
1. build the \Adafruit_nRF52_Arduino-master\libraries\Bluefruit52Lib\examples\Central\central_bleuart\
2. Verify that it successfully done.
3. Rebuild it again.
4. See error, it can be clear error like adafruit-nrfutil.exe does not exist or any other that you can find in the attached LOG file.
5. check \\arduino-nightly\\portable\\packages\\adafruit\\hardware\\nrf52\\0.16.0/tools/adafruit-nrfutil/win32/ for adafruit-nrfutil.exe. In case of error this file does not exist.
6. To resolve: copy adafruit-nrfutil.exe to the proper location:
.\\arduino-nightly\\portable\\packages\\adafruit\\hardware\\nrf52\\0.16.0/tools/adafruit-nrfutil/win32/ and build it again and see the successful result.
[err_log.txt](https://github.com/adafruit/Adafruit_nRF52_Arduino/files/4074418/err_log.txt)
[success_log.txt](https://github.com/adafruit/Adafruit_nRF52_Arduino/files/4074429/success_log.txt)
NOTES:
- in ARDUINO IDE selected Programmer: "Bootloader DFU for Bluefruit nrf52"
- sometimes it take a couple of times to reproduce the issue but it happen consistently. 

**Additional context**

**Comment by eduards66** [comment]
[err_log_1.txt](https://github.com/adafruit/Adafruit_nRF52_Arduino/files/4074509/err_log_1.txt)

exec: "\\arduino-nightly\\portable\\packages\\adafruit\\hardware\\nrf52\\0.16.0/tools/adafruit-nrfutil/win32/adafruit-nrfutil.exe": file does not exist
Error compiling for board Adafruit Bluefruit Feather nRF52832.

**Comment by hathach** [comment]
please check to see if the exe file is blocked by your anti-virus, there is a previous report that McAfee block nrfutil

**Comment by eduards66** [comment]
No, McAfee does not block it...

**Comment by eduards66** [comment]
Sorry, accidentally closed it, then reopen again...

**Comment by hathach** [comment]
adafruit-nrfutil existed but then removed from your system, please check to see which process delete it and why. It is possible that your pc mis-identify it as malicious ware. I don't know what we can do to resolve this.

**Comment by eduards66** [comment]
it is deleted after every single build, then it is not related to background pc activity.

**Comment by hathach** [comment]
And have you figured out why and what remove it ?

**Comment by eduards66** [comment]
1. downloaded  Adafruit_nRF52_Arduino-master from https://github.com/adafruit/Adafruit_nRF52_Arduino
2. copied its content to ...\nrf52\0.16.0\
3.  substituted  adafruit-nrfutil.exe with the latest from https://github.com/adafruit/Adafruit_nRF52_nrfutil/releases
=== Can not reproduce BUG anymore ===

**Comment by hathach** [comment]
I am glad you work it out.
