### ISSUE TITLE
How to send data in same format over BLE as over Serial ?

### ISSUE THREAD

**Issue by bossesand** [adafruit/Adafruit_nRF52_Arduino#43]
I am trying to modify BLEuart example

I Have a question, Why is the cmdMessenger message over BLE Separating each character on a new line?
I hope the cmdMessage is sent as one "string" as in this case it is shorter than 20 bytes!!!
If not how should the code be changed?

I Have a question, Why is the cmdMessenger message over BLE Separating each character on a new line?
I hope the cmdMessage is sent as one "string" as in this case it is shorter than 20 bytes!!!
If not how should the code be changed?

Result 1 with 
CmdMessenger cmdMessenger = CmdMessenger(Serial);
rest same as below...

Result 2
Code extract

#include <bluefruit.h>
#include "BNO055.h"
#include <CmdMessenger.h>  // CmdMessenger
#include <SPI.h>
#include <Wire.h>
...
// BLE Service
BLEDis  bledis;
BLEUart bleuart;
BLEBas  blebas; 
...
CmdMessenger cmdMessenger = CmdMessenger(bleuart);

  short Q0 = mySensor.quat.q0;
  short Q1 = mySensor.quat.q1;
  short Q2 = mySensor.quat.q2;
  short Q3 = mySensor.quat.q3;
  
  cmdMessenger.printLfCr(true);

  Serial.println("IMU Print");
  bleuart.println("IMU Print");
  
  cmdMessenger.sendCmdStart(kQuarternionSend);
  cmdMessenger.sendCmdBinArg(Q0);
  cmdMessenger.sendCmdBinArg(Q1);
  cmdMessenger.sendCmdBinArg(Q2);
  cmdMessenger.sendCmdBinArg(Q3);
  cmdMessenger.sendCmdEnd(); 
  
Result 1 on serial Monitor 
IMU Print
2,//,//,//,//;

Result 2 on nRF UART 2.0

RX: IMU Print
RX: 
RX: 2
RX: ,
RX: /
RX: 
RX: /
RX: 
RX: ,
RX: /
RX: 
RX: /
RX: 
RX: ,
RX: /
RX: 
RX: /
RX: 
RX: ,
RX: /
RX: 
RX: /
RX: 
RX: ;
RX:

**Comment by hathach** [comment]
please post in forum for support
