### ISSUE TITLE
MCP23S17 SPI No longer works

### ISSUE THREAD

**Issue by sysdevmike** [adafruit/Adafruit_nRF52_Arduino#446]
MCP23S17 SPI IO Expander stopped working properly on recent versions with a nrf52840.

Worked fine on the nrf52832. Worked but buggy < 0.14.5. Doesn't work after 0.14.5.

Baud rate issue?

**Comment by hathach** [comment]
thanks for reporting, can you provide more detail
- which  MCP23S17 board that you use to test with
- a simplest sketch that can reproduce the issue.

**Comment by sysdevmike** [comment]
Sorry, my fault. Thanks for getting back to me regardless.
