### ISSUE TITLE
Arduino IDE claims 0.18.0 can be updated, but no newer version available

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_nRF52_Arduino#450]
I'm getting an update notice from Linux Arduino IDE 1.8.12 that this BSP needs to be updated, but I have 0.18.0 installed, and there's no newer version. So maybe there's a version skew somewhere?

**Comment by colindgrant** [comment]
In case it's useful to have as a datapoint:
Arduino 1.8.11 on Mac Mojave allowed me to fresh-install 0.18.5 today:

![image](https://user-images.githubusercontent.com/2702617/76471684-9e553680-63b0-11ea-8431-dd644f57b829.png)

**Comment by hathach** [comment]
thanks @colindgrant for confirmation, @dhalbert that is weird, there should be an 0.18.5, which OS you are on !? I will check it out.

**Comment by dhalbert** [comment]
This is on Ubuntu 20.04 (but I was having the same trouble on 18.04). The BSP is listed as updatable, but the new version isn't visible. Like @colindgrant, I installed the BSP on a new installation of Arduino on another Ubuntu 20.04 computer, and it did install 0.18.5

![Screenshot from 2020-03-11 22-24-00](https://user-images.githubusercontent.com/2847802/76481173-32da8b80-63e7-11ea-9d40-2d90b8bbc29f.png)

**Comment by hathach** [comment]
@dhalbert this is headache, I have no clues atm. I just release 0.19.0 https://github.com/adafruit/arduino-board-index/pull/61 . Let's wait until tomorrow to see if it is updated

**Comment by colindgrant** [comment]
One last datapoint in case it's useful: I was able to install 0.19.0 and now I'm on 0.20.1, both installed via Arduino IDE with no apparent issue. MacOS Mojave/10.14.6, Arduino 1.8.12.

**Comment by hathach** [comment]
I just upgraded my PC to ubuntu 20.04, everything seems to be fine now. This should be closed, can be reopened if anyone still has issue with it.
