### ISSUE TITLE
Macro expansion of ARDUINO_BSP_VERSION from platform.txt fails

### ISSUE THREAD

**Issue by toxynoid** [adafruit/Adafruit_nRF52_Arduino#461]
Someone could argue I am wrong here because my IDE is cdt-arduino but this is somehow Adafruit related.

The Makefile in my projects build directory, that gets created from
`~/.arduinocdt/packages/adafruit/hardware/nrf52/0.18.5/platform.txt` 
contains a macro `-DARDUINO_BSP_VERSION="0.18.5"` that fails expanding in c/c++ code with error `too many decimal points in number` for example in
`~/.arduinocdt/packages/adafruit/hardware/nrf52/0.18.5/libraries/Bluefruit52Lib/src/services/BLEDis.cpp`
 
**Setup**
  - Bluefruit Feather nRF52840 Express
  - BSP Version 0.18.5
  - Ubuntu 19.04

**Working solution**
In above mentioned file platform.txt change
`-DARDUINO_BSP_VERSION="{version}"`
to
`-DARDUINO_BSP_VERSION=\"{version}\"`

**May be better solution**

In BLEDis.cpp

```
52c52,54
<   this->setSoftwareRev(ARDUINO_BSP_VERSION);
---
> #define XSTR(x) STR(x)
> #define STR(x) #x
>   this->setSoftwareRev(XSTR(ARDUINO_BSP_VERSION));
```

in debug.cpp

```
149,151c149
< #define XSTR(x) STR(x)
< #define STR(x) #x  
<   printf("BSP Library : " XSTR(ARDUINO_BSP_VERSION) "\n");
---
>   printf("BSP Library : " ARDUINO_BSP_VERSION "\n");
```
Sorry for the lazy diff and thanks in advance.

**Comment by hathach** [comment]
fixed by #471
