### ISSUE TITLE
Serial.print to USB Serial blocked by subsequent while(1)

### ISSUE THREAD

**Issue by colindgrant** [adafruit/Adafruit_nRF52_Arduino#505]
**Describe the bug**
I found a situation where an nRF52840 attempts to `Serial.print("txt")` but the "txt" never makes it to the serial monitor. It appears to be blocked forever by a subsequent call to loop with `while(1)`.

Using a FTDI Friend on Serial1 does print the message as expected.
Other micros running the same code print to the serial monitor before looping.

Found while testing https://github.com/adafruit/RTClib/pull/166 on:
Feather M4 Express
Feather nRF52840 Sense
Arduino Mega

The pertinent code looks like this:
```
  if (! rtc.begin()) {
    Serial.println("Couldn't find RTC");
    while (1);
  }
```

When `rtc.begin()` returns false, the nRF52840 begins looping without printing to serial monitor.
The M4 (which also uses native USB Serial I believe) and the Mega print before looping.

**It's as if the message is buffered and there is no time to get it out through USB before entering the loop, and no ability to interrupt the loop to send it once inside.**

Interestingly I found either of these two workarounds make the nRF52840 print as expected:
```
  if (! rtc.begin()) {
    Serial.println("Couldn't find RTC");
    Serial.flush(); // ensure above text prints with nRF52 native USB Serial
    while (1);
  }
```
```
  if (! rtc.begin()) {
    Serial.println("Couldn't find RTC");
    while (1) delay (1); // ensure above text prints with nRF52 native USB Serial
  }
```

**Set up**
  - Feather nRF52840 Bluefruit Sense
  - Bootloader 0.3.2 - 2020.03.12
  - BSP 0.20.1
  - Arduino 1.8.12
  - MacOS Mojave 10.14.6
  - RTClib at this commit:
https://github.com/adafruit/RTClib/pull/166/commits/3f379ab1a2a6e47066178b2838f4ecc7e282e680
  - RTClib/examples/pcf8523.ino

**To Reproduce**
```
void setup() {
    Serial.begin(57600);
    while (!Serial); // wait for serial port to connect. Needed for native USB
    Serial.println("Couldn't find RTC"); // this text will not print to Serial monitor
    while (1);
}
```

**Expected behavior**
I expect that Serial.print() will either block or interrupt a loop like `while(1)` so that it can empty its pending buffer.

Thank you for reviewing this issue, let me know how I can be of service, and thank you in general for all your hard work on this core!

**Comment by hathach** [comment]
you check out the answer here
https://github.com/adafruit/Adafruit_TinyUSB_Arduino/issues/51

> I expect that Serial.print() will either block or interrupt a loop like while(1) so that it can empty its pending buffer.

Neither is true, print() complete when it successfully write to tinyusb internal fifo, you need to manual Serial.flush() , else it will buffer until next time you give up CPU time with delay()/yield(). TinyUSB is thread-safe, and won't run its processing code in interrupt. You should quit `while(1) ;` and use `while(1) yield();` that will allow background task to run.
