### ISSUE TITLE
HardFault handler with debug output (registers, stacktrace, etc...) Do you want a PR?

### ISSUE THREAD

**Issue by geeksville** [adafruit/Adafruit_nRF52_Arduino#511]
**Is your feature request related to a problem? Please describe.**
The current hard fault handler just reboots the board, for my [mesh radio project,](https://github.com/meshtastic/Meshtastic-device) I made a nicer fault handler that prints out the stuff needed to debug NPEs etc... If you want it I can clean it up a bit and send it in as a PR.

**Comment by hathach** [comment]
yes, please make an PR, I am happy to review and merge it. Those are always very useful when troubleshooting.

**Comment by geeksville** [comment]
Ok will do sometime in the next weekish.

**Comment by hathach** [comment]
closed due to lack of activities
