### ISSUE TITLE
Connecting multiple devices to a GATT service unsubscribes them.

### ISSUE THREAD

**Issue by eraguzin** [adafruit/Adafruit_nRF52_Arduino#517]
**Describe the bug**
I've used the blueart_multi.ino sketch to have 2 devices connect to the same nRF52. Now, I'm trying to connect 2 devices to the same GATT service on the same nRF52. I merged blueart_multi.ino and custom_hrm.ino like here:
[https://forums.adafruit.com/download/file.php?id=75145](https://forums.adafruit.com/download/file.php?id=75145)

The first device connects and subscribes to the characteristic. The second one connects and the first device is spontaneously unsubscribed from the characteristics without any notice from the "disconnect callback" function.

**Set up (please complete the following information)**
  - I'm using the standard Adafruit nRF52 Arduino board, BSP is 0.18.5
  - Windows 10
  - Error Log is:
```
    -----------------------
    Initialise the Bluefruit nRF52 module
    Setting Device Name to 'Feather52 HRM'
    Configuring the Device Information Service
    Configuring the Battery Service
    Configuring the Heart Rate Monitor Service
    Setting up the advertising payload(s)
    Ready Player One!!!
    Advertising
    Connected to moto g(6)
    Connection count: 1
    Keep advertising
    ERROR: Notify not set in the CCCD or not connected!
    ERROR: Notify not set in the CCCD or not connected!
    CCCD Updated: 1
    Heart Rate Measurement 'Notify' enabled
    Heart Rate Measurement updated to: 20
    Heart Rate Measurement updated to: 21
    Heart Rate Measurement updated to: 22
    Heart Rate Measurement updated to: 23
    Heart Rate Measurement updated to: 24
    Heart Rate Measurement updated to: 25
    Heart Rate Measurement updated to: 26
    Heart Rate Measurement updated to: 27
    Heart Rate Measurement updated to: 28
    Heart Rate Measurement updated to: 29
    Heart Rate Measurement updated to: 30
    Heart Rate Measurement updated to: 31
    Heart Rate Measurement updated to: 32
    Connected to iPad
    Connection count: 2
    ERROR: Notify not set in the CCCD or not connected!
    ERROR: Notify not set in the CCCD or not connected!
    ERROR: Notify not set in the CCCD or not connected!
    ERROR: Notify not set in the CCCD or not connected!
```
**To Reproduce**
Run this .ino sketch:
[https://forums.adafruit.com/download/file.php?id=75145](https://forums.adafruit.com/download/file.php?id=75145)
and connect to it with 2 devices.

**Expected behavior**
I would expect the second device to connect with the original device keeping its subscriptions. I'm wondering if it's something in the backend code that handles connections.

**Comment by hathach** [comment]
you have to use the multiple connection notify API, the one with the conn_handle
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/src/BLECharacteristic.h#L158
