### ISSUE TITLE
Removed FreeRTOS version

### ISSUE THREAD

**Issue by atc1441** [adafruit/Adafruit_nRF52_Arduino#518]
Hi so i am using the Core on an nrf52832 and nrf52840 Smartwatch with the FreeRTOS enabled and it works like it should but as is allready known the power consumtion is not optimised.

So i am using the Old SD2.0.1 Sandeepmistry core and there the power consumption is like intended.

I removed the FreeRTOS of off the newest Adafruit nRF52 core and also get the wanted power consumption. 

Only problem is i can not use the BLElibrary with it as it has the FreeRTOS to hard implemented. So i am without BLE for this core at the moment wich is not very useable.

So my question is, is there any BLElibrary for this core without the FreeRTOS implementation?

Here is my project: https://github.com/atc1441/ATCwatch

**Comment by hathach** [comment]
> So my question is, is there any BLElibrary for this core without the FreeRTOS implementation?
No, we don't know any. Please post your question on support forum, there are more people there to discuss
