### ISSUE TITLE
Redeclaration of BLECharacteristic::write32(int)

### ISSUE THREAD

**Issue by dzervas** [adafruit/Adafruit_nRF52_Arduino#520]
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/b5f5bdd1e9debd0c8581e0047f6c2e1074e32127/libraries/Bluefruit52Lib/src/BLECharacteristic.cpp#L562-L570

`write32` is implemented for both `int` and `int32_t` - isn't this practically a redeclaration?

I have no problem compiling the library, but when I try to generate Rust bindings using bindgen I get (internally uses clang):

```
/home/dzervas/.platformio/packages/framework-arduinoadafruitnrf52/libraries/Bluefruit52Lib/src/BLECharacteristic.h:132:14: error: class member cannot be redeclared
/home/dzervas/.platformio/packages/framework-arduinoadafruitnrf52/libraries/Bluefruit52Lib/src/BLECharacteristic.h:131:14: note: previous declaration is here
```

I know though that my use case is very specific and if it causes problems it's better if this doesn't get fixed.

**Comment by hathach** [comment]
thanks for opening the issue, I made an PR to remove the int32_t variant, will merge if all checks are passed.
