### ISSUE TITLE
print log on RTT like NRF_LOG_INFO!

### ISSUE THREAD

**Issue by tusharvb19** [adafruit/Adafruit_nRF52_Arduino#541]
Not the debugging but, simple printing on RTT is what I am looking for. This will be very helpful.
I tried to find RTT in the repo but couldn't get any example, though I found some implementation here -
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/569b9b21e600d8fbcaddd9f978ae0ec7e87ae5d6/cores/nRF5/sysview/SEGGER/SEGGER_RTT.c

**Comment by pyro9** [comment]
if you #include <SEGGER_RTT.h> in your sketch, you can use SEGGER_RTT_PutChar(0,c)
where 0 is the terminal number and c is a character.

**Comment by tusharvb19** [comment]
Thanks. Will use SEGGER_RTT_WriteString instead.
