### ISSUE TITLE
v20.5 doesn't compile when Bluefruit.h is included

### ISSUE THREAD

**Issue by SuperSnake427** [adafruit/Adafruit_nRF52_Arduino#548]
in HID.h there are additional commas after the following two lines that need to be removed for the code to compile.

#define HID_REPORT_ID(x)          HID_REPORT_ITEM(x, 8, RI_TYPE_GLOBAL, 1) **,**
#define HID_REPORT_ID_N(x)        HID_REPORT_ITEM(x, 8, RI_TYPE_GLOBAL, n) **,**

**Comment by hathach** [comment]
please fill out all the questions in the template. Once you done, you could reopen the issue.
