### ISSUE TITLE
[nRF52840 DK][PCA10056] Debugger/Execution stuck on vPortStartFirstTask()

### ISSUE THREAD

**Issue by LaBus3** [adafruit/Adafruit_nRF52_Arduino#559]
IDE: Platfrom IO VScode
Board: nRF52840 DK
Sketch: Blink
BSP: Adafruit
Issue: No task gets executed, SVChandler not getting triggered.
Execution remains in vPortStartFirstTask() and does not move out.

I'm new to this platform so any help to get set up is appreciated.

**Comment by hathach** [comment]
for help please post to our forum support
