### ISSUE TITLE
Infinite loop in notify32

### ISSUE THREAD

**Issue by eugeneanikin** [adafruit/Adafruit_nRF52_Arduino#569]
Line 727 in BLECharacteristic.cpp is a typo. It should be:
725 bool BLECharacteristic::notify32(uint16_t conn_hdl, int num)
726 {
727  return notify(conn_hdl, (uint8_t*) &num, sizeof(num));
728 }
Thank you,
Eugene

**Comment by hathach** [comment]
ah right, thank you for spotting the issue. Fixing it right away.
