### ISSUE TITLE
Nordic Led Button service as optional library

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Arduino#59]
Implement as optional library. It is still useful since Nordic make an easy to use app. Some user that want simple toggle control over device can find this useful
https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfblinky&hl=en

**Comment by microbuilder** [comment]
If it isn't a lot of effort to implement, it might be a useful example to add via a helper class.

**Comment by hathach** [comment]
there is no iOS equivalent for nrf Blinky app, making things less convenient (which is the main reason we port it), just postpone this issue until there is a good app for iOS
