### ISSUE TITLE
Software Serial

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Arduino#62]

**Comment by hathach** [comment]
ported

**Comment by micooke** [comment]
@hathach - does SoftwareSerial work for this core? Im using a different core and had an issue where it stalled apon a serial  write/print. It ended up being an issue with defines in arduino.h, which caused a seg fault. If you are interested, here's the link : https://github.com/sandeepmistry/arduino-nRF5/issues/98#issuecomment-336750882

**Comment by hathach** [comment]
it works on this core
