### ISSUE TITLE
peripheral pairing_pin Example doesn't compile

### ISSUE THREAD

**Issue by ericlangel** [adafruit/Adafruit_nRF52_Arduino#628]
**Describe the bug**
peripheral pairing_pin Example doesn't compile
there are many headers not found 

**Set up (mandatory)**
 - **PC & IDE** : Arduino 1.8.13 Windows 10
 - **BSP**   : 0.21.0 (Master)
 - **Board** : Feather nRF52832
 - **Sketch**: Bluefruit52Lib/examples/Peripheral/pairing_pin

**To Reproduce**
compile sketch with actual master branch

**Serial Log**

when i open the sketch -> i get an info in command window that there is no Header file in Adafruit_nrfCrypto

when i compile the sketch -> common/tusb_compiler no such file or directory

[Error.txt](https://github.com/adafruit/Adafruit_nRF52_Arduino/files/6276756/Error.txt)

**Comment by ericlangel** [comment]
same for bleuart example

common/tusb_compiler.h is missing?

is there a working example for pairing_pin?

**Comment by hathach** [comment]
firstly please clean up your 1st post and have compile log in its own txt file.

**Comment by jpconstantineau** [comment]
Quick comment: the nrf52832 does not have a cryptocell nor USB.  Why then is this trying to compile wit Adafruit_nRFCrypto and Tinyusb?  This is probably why it's not compiling...

**Comment by ericlangel** [comment]
@hathach sorry, i did clean it

@jpconstantineau same for Feather NRF52840 Express

**Comment by hathach** [comment]
@ericlangel you need to clone the TinyUSB core submodule as well, download zip file won't do the trick.

```
Clone this repo & its submodules: git clone --recurse-submodules https://github.com/adafruit/Adafruit_nRF52_Arduino.git
```
