### ISSUE TITLE
Add RSSI filter to scan results

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_nRF52_Arduino#63]
When we start the scanning process, we should add an optional argument to specify an RSSI filter. 

Any value <= the specified RSSI value will be ignored and the callback won't be fired. This will make it easier to only see data from devices that are nearby.

This can either be an optional argument in `Bluefruit.Scanner.start(...)` or or a new function like `Bluefruit.Scanner.setRSSIFilter(int8_t min_rssi);`.

**Comment by hathach** [comment]
great idea, though, user can also simply write an 
if rssi < value

in the callback and return as well.

**Comment by hathach** [comment]
hmm, although it is doable in user callback, maybe we could extend the filter a bit e.g name contains a specific string and/or having uuid16 or uuid128. It is all about convenience.

**Comment by microbuilder** [comment]
I'd also like to filter by other values like the HW address, though, and having some filtering behind the scenes might keep code cleaner. This isn't urgent, though, I'm just filing it as a 'ToDo' and as the API gets the tires kicked in we can come back to it.
