### ISSUE TITLE
Warnings are generated during compilation

### ISSUE THREAD

**Issue by zfields** [adafruit/Adafruit_nRF52_Arduino#630]
**Describe the bug**
Warnings are generated during compilation.

**Set up (mandatory)**
 - **PC & IDE** : Arduino 1.8.13 on Ubuntu 20.04
 - **BSP**   : 0.21.0
 - **Board** : Feather nRF52840 Express
 - **Sketch**: Any
 
**To Reproduce**
1. Enable "Compiler warnings: All" in the Arduino IDE "File > Preferences" menu
2. Click on the check mark to compile
3. See warnings in build log.

It appears some, if not all, of the warnings have been remedied and are in `master`, but a new release hasn't been created since last August.

**Comment by hathach** [comment]
most of warnings has been addressed with latest code. Feel free to open new one with specific warnings
