### ISSUE TITLE
About Support ESB (Enhanced shock burst) mode. 

### ISSUE THREAD

**Issue by waromin** [adafruit/Adafruit_nRF52_Arduino#634]
I have used ESP8266 and ESP32, these have very useful connect-less protocol ESP-NOW.
But, these SoC's power consumption is pretty bigger than nrf52 series.

I want to send 10 byte sensor data from eight of nrf52 to one nrf52 with nearly 80 Hz.
ESP-now can process these data, but nrf52 with BLE notify cannot process and very slow rate :(

According to Nordic  user guides, nRF5 series have ESB (Enhanced Shock Burst) protocol.
I think ESB is very useful and good for transfer sensor data with high rate!
So, I tried to porting ESB from Nordic SDK to Arduino, but I miscarried it with my poor skill. ;)

Please support ESB....

**Comment by hathach** [comment]
I don't think we could have time to support ESB, you really need to use nordic sdk with C to get it done. Any PR is welcome though.
