### ISSUE TITLE
Adafruit ItsiBitsy nRF52840 Express hangs completely when using Fabrik2D library

### ISSUE THREAD

**Issue by xchg-dot-ca** [adafruit/Adafruit_nRF52_Arduino#638]
**Describe the bug**
When using Fabrik2D library and trying to solve inverse kinematic scenario board hangs and requires hold reset procedure to reflsah.
I assume board enters an infinite loop. I believe there is some kind of imperfection in double/float math library of the board.
This issue is NOT happening on: Arduino UNO, Arduino Leonardo, Teensy 3.1, Arduino Due

**Set up (mandatory)**
 - **PC & IDE** : Arduino 1.8.13 on Windows 7
 - **BSP**   : 0.2.11 SoftDevice s140 6.1.1
 - **Board** : Adafruit ItsiBitsy nRF52840 Express
 - **Sketch**: Test sketch attached

**To Reproduce**
Please install attached library or install it via the Library manager of the IDE
Compile and Upload attached sketch
[example_3DOFToolAngle.zip](https://github.com/adafruit/Adafruit_nRF52_Arduino/files/6479518/example_3DOFToolAngle.zip)
[Fabrik2D.zip](https://github.com/adafruit/Adafruit_nRF52_Arduino/files/6479523/Fabrik2D.zip)

**Screenshots**
n/a

**Serial Log**
n/a

**Comment by xchg-dot-ca** [comment]
Disregard, issue was specifically with library not having return statement:
https://github.com/henriksod/Fabrik2DArduino/pull/20

Still interesting to see different behaviour for Adafruit library that it getting lost if not return statement provided in the code
In same time Arduino products work fine

**Comment by hathach** [comment]
I didn't look at the code, for this core, if you have 

```C
while(1) {}
```

it will entirely occupy the CPU and does not give any other task such as tinyusb to handle any printf, or touch1200. Making it is look like hanged. It is probably the case here. What you should do is adding either yield() or delay(1) in your blocking.

```C
while(1) yield(); // or delay(1)
```

**Comment by hathach** [comment]
Could be closed now
