### ISSUE TITLE
0.22 release?

### ISSUE THREAD

**Issue by jeffc** [adafruit/Adafruit_nRF52_Arduino#641]
Thanks for this amazing library! Would it be possible to cut a new official release? Some features that I'd like to use (such as #594 ) have been added since last August when the 0.21 release was tagged, and I'd like to avoid using an untagged version for my project if possible. 

It would also be great if those features could make it into the platformio downstream (I recognize that's not your responsibility, but I suspect they'll just follow along with your releases).

Thanks again!

**Comment by hathach** [comment]
Soon, but please don’t ask question on github issue.
