### ISSUE TITLE
Only single service connection between two boards?

### ISSUE THREAD

**Issue by antonbrams** [adafruit/Adafruit_nRF52_Arduino#660]
Hi, i've following configuration:

"ItsyBItsy on the Left" {
- [1] is defined as a PERIPHERAL to communicate with the computer
-- running homemade service 0x0003
--- running its characteristics at 0x0004 (notify)
-- running another service 0x0005 
--- characteristics at 0x0006 (notify, write)
--- characteristics at 0x0007 (notify, write)
- [2] aswell defined as a CENTRAL to connect to another "ItsyBitsy on the Right"
-- want to connect to the service 0x0003
--- connect to characteristics at 0x004 (notify)
-- connect to the service 0x0005 
--- characteristics at 0x0006 (notify, write)
--- characteristics at 0x0007 (notify, write)
}

"Itsy Bitsy on the Right" {
- [1] is defined as a peripheral to communicate with the "ItsyBitsy on the Left"
-- running homemade service 0x0003
--- running its characteristics at 0x0004 (notify)
-- running another service 0x0005 
--- characteristics at 0x0006 (notify, write)
--- characteristics at 0x0007 (notify, write)
}

i share same codebase between boards, because the [1] service has the same behaviour on both sides. Only the central behaviour is enabled with #ifdef on the left side. I want to send a file to the left one, and from the left transmit to the right itsybity. So if i enable on both boards a single service, everything works. The problem is, if i enable two [1] services at once, and try to connect with [2] central service to the right half. The left size refuses to connect to more than one service of the right board. They are just both quite, no errors, console outputs, etc...

Is it a limitation of the system, or is it a bug?

- working on the mac 11.4, arduino 1.8.15
- boards 2x itsybitsy nrf52840

**Comment by hathach** [comment]
have you tried the dual role example which does something similar.  https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/examples/DualRoles/dual_bleuart/dual_bleuart.ino

**Comment by antonbrams** [comment]
Thank you for your answer. I still can't get it to work. On the way of testing i've found out that my Itsy Bitsy on the left should have same addresses in peripheral and central, otherwise it will interfere with itself and receive sent data )... anyway i've implemented a single service and put all the characteristics in it... not an intended ble design but heck it works and i move on with my project... if somebody had the same issue, then say it aloud ) thank you for your time

**Comment by hathach** [comment]
There is more people in support forum to help you there. And you should start with stock example then modify it. BLE is complicated

**Comment by jpconstantineau** [comment]
@antonbrams For my BlueMicro_BLE firmware, I have implemented a custom service for communication between halves of a split keyboard.  Unfortunately, not as two services.  Have you tried connecting to standard services and not custom ones?  For example one custom and the battery service? Or one custom and one Blueart?

**Comment by antonbrams** [comment]
> @antonbrams For my BlueMicro_BLE firmware, I have implemented a custom service for communication between halves of a split keyboard. Unfortunately, not as two services. Have you tried connecting to standard services and not custom ones? For example one custom and the battery service? Or one custom and one Blueart?

ah no, had no time to experiment so much. Even if it would work, the custom services that i need so much will still be unconnected )

**Comment by hathach** [comment]
enable debug level to 2 (via menu) could help you to understand more what activities behind the scene, and error if any
