### ISSUE TITLE
Bluefruit.begin() stops the e104-BT5032A based nrf52832 module

### ISSUE THREAD

**Issue by Fantonrko** [adafruit/Adafruit_nRF52_Arduino#669]
Hey! I start work with new for me module e104-BT5032A. I use ebyte_e104_bt5032a_bootloader-0.6.0 bootloader and change variant.h in package. All works fine but i can`t start work with BLE. I have the simple sketch and give part for test:
```
   Serial.println("-----------START-----------\n"); // i see it Serial port
   Bluefruit.begin(1, 1);
   Serial.println("-----------BEGIN-----------\n"); // i didn`t see this message in Serial port
   Bluefruit.setTxPower(4);
``` 
   
   And i didn`t see nrf52 device in my smartphone with nrf Connect or adafruit Connect apps

**Comment by hathach** [comment]
Please post your questions to support forum.
