### ISSUE TITLE
hardware PWM parameters

### ISSUE THREAD

**Issue by bmalloy-224** [adafruit/Adafruit_nRF52_Arduino#686]
**Is your feature request related to a problem? Please describe.**
 I don't see any way to set the DECODER, ENDDELAY, REFRESH, or LOOP. It all seems hard coded.
**Describe the solution you'd like**
Add the ability to change the hwPWM parameters,

**Describe alternatives you've considered**
Changing the settings for the bootloader

**Comment by hathach** [comment]
do you plan to make an PR to implement this ? I will be happy to review it.

**Comment by hathach** [comment]
closed due to lack of activities
