### ISSUE TITLE
support Tone() 

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Arduino#69]
implement later

**Comment by mennamorato** [comment]
@hathach When will Tone library be added to nRF52 for Arduino?  Thanks

**Comment by hathach** [comment]
No ETA at all :)

**Comment by mogar** [comment]
I second this request. If you have any pointers on getting started with implementing, I could work on a pull-request.

**Comment by hathach** [comment]
@mogar  may be primo could help https://github.com/arduino-org/arduino-core-nrf52/blob/master/cores/arduino/Tone.cpp

**Comment by ladyada** [comment]
@hathach we'll need this for CPB - lets implement soon, it's done with a timer not PWM

**Comment by hathach** [comment]
@ladyada please try with master branch to see if that works

**Comment by ladyada** [comment]
hmm tried this code on feather nrf52480 but no PWM on pin 5... does it work for you?

```
void setup() {

}

void loop() {
  pinMode(5, OUTPUT);
  tone(5, 4000, 100);
  delay(100);
}
```

**Comment by hathach** [comment]
@ladyada ah sorry, I somehow delete the line that trigger pwm by mistake (a very important line of code). please pull from master and try again

**Comment by ladyada** [comment]
done, tested - works great! thanks :)
