### ISSUE TITLE
Doen`t work SPIM3 on nRF52840 

### ISSUE THREAD

**Issue by Fantonrko** [adafruit/Adafruit_nRF52_Arduino#699]
Have enable SPIM3 like this 
`#define SPI_INTERFACES_COUNT 2
#define SPI_32MHZ_INTERFACE  1

#define PIN_SPI_MISO         (30)
#define PIN_SPI_MOSI         (39)
#define PIN_SPI_SCK          (37)`

But SPI speed is 8MHz on my oscilloscope. What`s i can do to use max 32MHz ?

**Comment by hathach** [comment]
this is not a feature, if you want to report an bug, please use the bug template. Otherwise, you could open an question in support forum.
