### ISSUE TITLE
Getting own Bluefruit peer address

### ISSUE THREAD

**Issue by daniellehu** [adafruit/Adafruit_nRF52_Arduino#71]
Is there a proper way to get the peer address of your own device? It looks like `Bluefruit.peerAddr().addr` would be the solution, but this prints out to `00:00:00:00:00:00` every time.

**Comment by hathach** [comment]
as it says, peerAddr() getting the address of the peer it connects to. We added the set/get Addr for the develop branch. Check out the printInfo that print out the summary. The call is `Bluefruit.Gap.getAddr()`

https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/develop/libraries/Bluefruit52Lib/src/bluefruit.cpp#L380
