### ISSUE TITLE
MTU is set to 527

### ISSUE THREAD

**Issue by ericlangel** [adafruit/Adafruit_nRF52_Arduino#720]
Hello,

i have found a strange Bug.

in Connect Callback i request a MTU Size of 247 with:
conn->requestMtuExchange(247);

before Notify i get the MTU to fill my array with:
Bluefruit.Connection(0)->getMtu();

With Android i get a Value of 247 -> as expected
With Windows and Bleak i get a Value of 527!

How is that possible?
I think that it is a Bug in Bleak, but how is it possible that Bluefruit is accepting a MTU Size of 527?
All Limits should be at 247

**Comment by hathach** [comment]
please use the bug template if you believe this is an bug
