### ISSUE TITLE
Bootloader J-Link issue (ERROR: The file specified is not a valid hex file)

### ISSUE THREAD

**Issue by tonialomar** [adafruit/Adafruit_nRF52_Arduino#751]
### Operating System

Windows 10

### IDE version

Arduino 1.8.19

### Board

Custom nRF52832QFAB

### BSP version

1.3.0

### Sketch

/examples/Basic/Blink

### What happened ?

I have a custom nRF52832 board.
Initially I tried to upload the bootloader to a nRF52832QFAA (Dollatek nRF52832 Board) and it worked perfectly. Everything works fine. Then I tried on mine and I got the following error:
`Parsing hex file.
ERROR: The file specified is not a valid hex file, has data outside valid areas
ERROR: or does not have data in valid areas.
Error quemando bootloader
`
I noticed its because I bought wrongly a nrf52832QFAB instead of QFAA and they differ in RAM/Flash size. 
I saw some pots out there where you can change the bootloader START ADDRESS and it works.

I was not able to solve it. I am using a J-Link progammer using Arduino.

How can I proceed?

Thanks,

Toni

### How to reproduce ?

Tools-->Burn Bootloader 

Softdevice S132 6.1.1
Adafruit Feather nRF52832

**Comment by hathach** [comment]
for question and how-to, please post in forum support.
