### ISSUE TITLE
Dual-bank firmware update

### ISSUE THREAD

**Issue by aqibnasim** [adafruit/Adafruit_nRF52_Arduino#756]
Hello, I am trying to achieve FOTA on my nrf52840 device over LTE using Quectel BG77 modem.

I want to achieve it by first writing the firmware to the nrf flash and update to the latest after restart. I see that nrf SDK has [dual-bank update](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v12.0.0%2Flib_bootloader_dfu_banks.html) feature .

I wanted to ask if the Arduino core for nrf has this feature? If not is there any upcoming update related to this? Thanks

**Comment by hathach** [comment]
This should be asked in https://github.com/adafruit/Adafruit_nRF52_Bootloader repo though. However, we don't use dual bank, since it halves the flash usage, and arduino user don't really like it.
