### ISSUE TITLE
NFC not working using your NFC examples and then stops working altogether

### ISSUE THREAD

**Issue by Gerriko** [adafruit/Adafruit_nRF52_Arduino#757]
### Operating System

Linux

### IDE version

Arduino 1.8.16

### Board

nRF8240-DK and nRF52840 Xenon board

### BSP version

github latest

### Sketch

NFC SendText example (I see it is no longer in the repository?)

### What happened ?

I flashed my 2 boards using the appropriate 0.7.0 bootloaders as found here: https://github.com/adafruit/Adafruit_nRF52_Bootloader/releases

In Arduino IDE I then selected the board either as "Nordic nRF52840 DK" or "Particle Xenon".

I then used the NFC example "SendText".

But nothing happens. The phone does not detect the antenna attached to either board.

Now, more worrying for me is that if I then flash these boards with a working example from the nRF52 SDK using my Segger JLink via Segger Embedded Studio, none of the NFC examples work when they all worked perfectly beforehand.

I cannot work out what has gone wrong.

Thanks

### How to reproduce ?

As described above.

**Comment by hathach** [comment]
NFC is probably converted to gpio purpose by the sketch/bootloader, try to do opposite for this sketch https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/examples/Hardware/nfc_to_gpio/nfc_to_gpio.ino
