### ISSUE TITLE
SoftwareSerial Selftest Echo

### ISSUE THREAD

**Issue by orbitinstasis** [adafruit/Adafruit_nRF52_Arduino#76]
Is it possible to use SoftwareSerial on pins other than A0 and A1?

I've got P0.30 and P0.31 setup as rx and tx respectively, looped back tx and rx of the usb's serial. Using the software serial example (changing the pins to 30,31) i'm able to see chatter on my scope, but nothing is echo'd back.

**Comment by hathach** [comment]
please post question on support forum. Github is for bug & feature tracking only, Thanks.
