### ISSUE TITLE
Add QEI Helper Class

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_nRF52_Arduino#77]
A helper class should be added for HW control of a simple rotary/quadrature encoder, tracking the absolute position, and recent changes (offset).

## Requirements

- [x] HW based using the QEI peripheral block
- [x] Track the absolute position over time, with an option to reset it in SW
- [ ] Track the changes since the last time a function like '.offset' (???) is called (separate from the total absolute value), returning separate positive and negative 'ticks' since you can turn both ways between reads.
- [x] Support an optional callback that fires whenever a change in position is detected

**Comment by microbuilder** [comment]
We can do something like this:

```
// Position functions
void qei.clearAbs(void);
int32_t qei.getAbsPos(void);
int32_t qei.getDelta(int32_t *ccw, int32_t *ccw); // Returns 'total' changes since last call to .getDelta (cw + ccw), and optionally allows reading the cw (clockwise) and ccw (counter-clockwise) tickes individualls, which is more detail than the combined results returned by the function

// Callbacks
void qei.setQeiCallback(int32_t cw, int32_t ccw); // cw or ccw tick callback
void qei.setSwitchCallback(uint8_t state); // swtich callback if switch is present
```
The constructor should optionally accept a GPIO pin if the switch is present and init and handle that accordingly.

**Comment by hathach** [comment]
both hw and sw encoder are added. It is a bit buggy but will be addressed by a separated issue.
