### ISSUE TITLE
OCF support

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Arduino#78]
related to #37 
reference

- https://openconnectivity.org/
- https://www.iotivity.org/documentation

**Comment by microbuilder** [comment]
IoTivity is an open source implementation of the OFC standard, and is probably the way to go here. As a sidenote, I believe Mynewt support is still based on the 1.11 release of IoTivity, though, so we may want to remain consistent with that codebase.

**Comment by microbuilder** [comment]
Here is a link to the Mynewt OIC code, just as a reference: https://github.com/apache/mynewt-core/tree/master/net/oic

NOTE: OIC has merged with OCF ... and is now called 'OCF', but you still run into the old 'OIC' name a lot since the merge was quite recent.

**Comment by hathach** [comment]
closed due to lack of activities
