### ISSUE TITLE
Maximal number of characteristics or attributes per BLE service?

### ISSUE THREAD

**Issue by simon-hauser** [adafruit/Adafruit_nRF52_Arduino#794]
Hi,

I'm having troubles with a couple of xiaos ble sense nrf82540 and BLE, where one of them is set up as a peripheral, and several others as centrals. I received the tip to set it up like this from another source, but I think for my problem this is irrelevant.

I first wanted to have several BLE services, and specific characteristics behind them. That didn't work, because the advertising can only advertise one 128-bit UUID due to the package size. 

Ok, that is not a problem, I can do one service and many characteristics. But now I run into another limit that I haven't figured out yet. Somehow I only see 9 characteristics, but I would have 22 in total. Is this a hardcoded limit somewhere, or it is something I could change? I saw in another library that the number of connection handles is initially set but can be changed (something like `BLEService *service = *service->createService(BLEUUID(SERVICE_UUID), 30, 0);` to put it to 30).

Apologies if this is not the right place to ask this. I'm just trying to find help, so far implementing BLE has been rather tricky for me and this is the last hurdle in a otherwise finally working application.

Best,
simon

**Comment by hathach** [comment]
for question, please use support forum or discussion
