### ISSUE TITLE
Support for Nice!Nano V2 Nordic nRF52840

### ISSUE THREAD

**Issue by astrolemonade** [adafruit/Adafruit_nRF52_Arduino#818]
**Is your feature request related to a problem? Please describe.**
I would like to use this library for Nice!Nano V2 that uses Nordic nRF52840 chip. The board is very popular in the keyboard making community(it's used to make bluetooth split keyboards and single device keyboards via ZMK firmware).

**Describe the solution you'd like**
Some support in this library for this board.

**Describe alternatives you've considered**
I tried other cores of the nRF52 but I none had official support for this board.

**Additional context**
Website of the board: https://nicekeyboards.com/nice-nano
There are a schematic and a pinout for it: https://nicekeyboards.com/docs/nice-nano/pinout-schematic for both V1 and V2(but only V2 is still commercialized). There is more info here: https://nicekeyboards.com/docs/nice-nano. It is mentioned that the board is using https://github.com/adafruit/Adafruit_nRF52_Bootloader bootloader.
I would gladly help with testing if you decide to add support for it.
There is already support for it in Circuit Python here: https://circuitpython.org/board/nice_nano .
Thank you!

**Comment by jpconstantineau** [comment]
Nice Nano support is available here: https://github.com/nRF52-Arduino/nRF52_Arduino.
Not sure if it's the V1 or V2 or if it's the same for both.
