### ISSUE TITLE
High Throughput (2 Mbps PHY) support

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Arduino#83]
ref https://www.nordicsemi.com/eng/Products/Bluetooth-5
ref https://www.novelbits.io/bluetooth-5-speed-maximum-throughput/ 

**Higher data throughput**

The data rate for Bluetooth low energy has now been extended from a singular transmission speed (1Mbs) to four discrete data rate speeds as seen in the list above. The maximum speed is doubled to 2Mbs. Together with advancements introduced in Bluetooth 4.2 which allowed for Data Length Extensions (DLE) overall throughput is x5 higher than the original Bluetooth 4.0 level. Now net data throughput not including overhead such as addressing can be as high as 1.4Mbs. Data packet size, datarate and overall data throughput are illustrated in fig. 1.

**Comment by hathach** [comment]
implemented #324

**Comment by ApoorvaSheth** [comment]
I wanted to know if the long-range feature is supported in BlueFruit library for nRF52840 express.
