### ISSUE TITLE
Confusing/different nrfutil installation path

### ISSUE THREAD

**Issue by dlopuch** [adafruit/Adafruit_nRF52_Arduino#87]
The section on the main readme to install nrfutil says:

> Go into the BSP folder (`hardware/Adafruit/Adafruit_nRF52_Arduino/tools/nrfutil-0.5.2`)...

With Arduino IDE 1.8.5 on OS-X sierra, I finally found the tools in:

`~/Library/Arduino15/packages/adafruit/hardware/nrf52/0.7.5/tools/nrfutil-0.5.2`

So, the path from `hardware/` on is different, but it also took some digging to realize to look in `~/Library/Arduino15`.   The latter might be obvious to experienced arduino users, but a bit unclear to this greenhorn.  Would submit a PR but not sure how much of this is version/env specific.

Also, the [Bluefruit NRF52 learning guide](https://learn.adafruit.com/bluefruit-nrf52-feather-learning-guide/arduino-board-setup) doesn't seem to mention the step of installing nrfutil -- you get IDE errors about not finding `/usr/local/bin/nrfutil` until you run that step. Might want to update that guide as well.

**Comment by hathach** [comment]
already mentioned here https://learn.adafruit.com/bluefruit-nrf52-feather-learning-guide/arduino-bsp-setup#nrfutil-os-x-and-linux-only
