### ISSUE TITLE
Custom_HRM Example — Prototype Consistency with Function?

### ISSUE THREAD

**Issue by rei-vilo** [adafruit/Adafruit_nRF52_Arduino#95]
In the example [`custom_hrm.ino`](https://github.com/adafruit/Adafruit_nRF52_Arduino/tree/10a9af52aaa3b64e5f3832e008013d0b833f60da/libraries/Bluefruit52Lib/examples/Peripheral/custom_hrm), there is a prototype on line 25 from function `cccd_callback()`:

https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/10a9af52aaa3b64e5f3832e008013d0b833f60da/libraries/Bluefruit52Lib/examples/Peripheral/custom_hrm/custom_hrm.ino#L35

Shouldn't the prototype be instead

```
void cccd_callback(BLECharacteristic& chr, uint16_t cccd_value) ;
```

to be consistent with line https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/10a9af52aaa3b64e5f3832e008013d0b833f60da/libraries/Bluefruit52Lib/examples/Peripheral/custom_hrm/custom_hrm.ino#L187

**Comment by hathach** [comment]
thanks for reporting the issue, you have an eagle eye :D . Just fix it, will be part of the next release.
