### ISSUE TITLE
Increasing the number of BLE connections?

### ISSUE THREAD

**Issue by ynohtna92** [adafruit/Adafruit_nRF52_Arduino#96]
Based on this line [here](https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/10a9af52aaa3b64e5f3832e008013d0b833f60da/libraries/Bluefruit52Lib/src/bluefruit.h#L50), would it be feasible to increase this number to 7? What else needs to be changed to do so? Are you able to also comment on the ram requirements that each connection is required to have?

**Comment by hathach** [comment]
The next release that upgrade S132 to v5 could support up to 20 connections. The only limit is ram usage that need different linker script for each max connections. We could support max connections with one linker but that will hugely reduce the SRAM for 90% of other use case. 

If you couldn't wait, check Nordic documents for S132 v2 connection vs sram usage.

PS: github is for feature and bug fix, questions go to our forums.
