### ISSUE TITLE
Example blink_timer_callback incorrectly toggling on count change

### ISSUE THREAD

**Issue by ynohtna92** [adafruit/Adafruit_nRF52_Arduino#98]
For the [blink_timer_callback function](https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/examples/Central/central_bleuart_multi/central_bleuart_multi.ino#L301-L314) in the central_bleuart_multi.ino example the logic is wrong in toggling the digital output for a changing connection_num.

If the connection_num decrements whilst the output is toggled on. It will not toggle off again for the second polling and become inverted.

A quick solution is to check to see if this is inverted and correct it on an odd number count with the following code below.

``` diff
void blink_timer_callback(TimerHandle_t xTimerID)
{
  (void) xTimerID;

  // Period of sequence is 10 times (1 second). 
  // RED LED will toggle first 2*n times (on/off) and remain off for the rest of period
  // Where n = number of connection
  static uint8_t count = 0;

  if ( count < 2 * connection_num) digitalToggle(LED_RED);
+ if ( count % 2 && digitalRead(LED_RED)) digitalWrite(LED_RED, LOW);

  count++;
  if (count >= 10) count = 0;
}
```

Sorry for the issue spam. I'm just trying to make the library as good as it can be. 😃

**Comment by hathach** [comment]
thanks for reporting the issue, we will test and it include this in the next release when confirmed. Don't worry about the number of issues. You could create as many as you want. We encourage people to report bugs and request features on github. Even those that are not likely to be implemented in near future :D
